/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FarmSetupRouteImport } from './routes/farm-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewReadingRouteImport } from './routes/new-reading'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmSetupRoute = FarmSetupRouteImport.update({
  id: '/farm-setup',
  path: '/farm-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReadingRoute = NewReadingRouteImport.update({
  id: '/new-reading',
  path: '/new-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/farm-setup': typeof FarmSetupRoute
  '/login': typeof LoginRoute
  '/new-reading': typeof NewReadingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/farm-setup': typeof FarmSetupRoute
  '/login': typeof LoginRoute
  '/new-reading': typeof NewReadingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/history/$id': typeof HistoryIdRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/farm-setup': typeof FarmSetupRoute
  '/login': typeof LoginRoute
  '/new-reading': typeof NewReadingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/farm-setup'
    | '/login'
    | '/new-reading'
    | '/profile'
    | '/results'
    | '/signup'
    | '/history/$id'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/farm-setup'
    | '/login'
    | '/new-reading'
    | '/profile'
    | '/results'
    | '/signup'
    | '/history/$id'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/farm-setup'
    | '/login'
    | '/new-reading'
    | '/profile'
    | '/results'
    | '/signup'
    | '/history/$id'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FarmSetupRoute: typeof FarmSetupRoute
  LoginRoute: typeof LoginRoute
  NewReadingRoute: typeof NewReadingRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-setup': {
      id: '/farm-setup'
      path: '/farm-setup'
      fullPath: '/farm-setup'
      preLoaderRoute: typeof FarmSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-reading': {
      id: '/new-reading'
      path: '/new-reading'
      fullPath: '/new-reading'
      preLoaderRoute: typeof NewReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FarmSetupRoute: FarmSetupRoute,
  LoginRoute: LoginRoute,
  NewReadingRoute: NewReadingRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
